const cv=document.querySelector('#cake'),ctx=cv.getContext('2d'),controls=document.querySelector('#controls');
let step=1,selected=null,gesture=null;const cache={};
const state={bg:'#f1d7d3',cake_type:'whole',objects:[],candles:[],title:'',nickname:'',country:'',letter:'',letterTemplate:'paper'};
const cakeAssets={whole:'/assets/v04-cake-whole.svg',slice:'/assets/v04-cake-piece.svg',cut:'/assets/v04-cake-cut.svg','two-tier':'/assets/v04-cake-two-tier.svg'};
const stickers=[['Maltese','v04-maltese-01'],['Maltese ♥','v04-maltese-02'],['Maltese Shades','v04-maltese-03'],['Maltese Party','v04-maltese-04'],['Maltese Rest','v04-maltese-05'],['Maltese Back','v04-maltese-06'],['Whale','v04-whale'],['Whale Splash','v04-whale-02'],['Whale Heart','v04-whale-03'],['Whale Hat','v04-whale-04'],['Strawberry','v04-strawberry'],['Blueberry','blueberry'],['Cherry','cherry'],['Lemon','v04-lemon'],['Grapes','v04-grapes'],['Watermelon','v04-watermelon'],['Cucumber','v04-cucumber'],['Rose','v04-rose'],['Tulip','v04-tulip'],['Daisy','v04-daisy'],['Clover','v04-clover'],['Ribbon Blue','v04-ribbon'],['Ribbon Pink','v04-ribbon-pink'],['Heart','heart'],['Sunglasses','v04-sunglasses'],['Palette','v04-paint'],['Brush','v04-brush'],['Paint Tube','v04-paint-tube'],['Camera','v04-camera'],['Music','v04-music'],['Chihuahua','chihuahua'],['German Shepherd','shepherd']];
const candleAssets=[['Classic','v04-candle-classic'],['Heart','v04-candle-heart'],['Dog','v04-candle-dog'],...Array.from({length:10},(_,i)=>[String(i),`number-${i}`])];
const countries=[['','선택 안 함'],['KR','South Korea'],['JP','Japan'],['US','United States'],['CN','China'],['TW','Taiwan'],['HK','Hong Kong'],['TH','Thailand'],['PH','Philippines'],['ID','Indonesia'],['MY','Malaysia'],['SG','Singapore'],['VN','Vietnam'],['GB','United Kingdom'],['FR','France'],['DE','Germany'],['ES','Spain'],['IT','Italy'],['CA','Canada'],['AU','Australia'],['BR','Brazil'],['MX','Mexico']];
const titles=['Make a Cake','Make a Deco','Make a Candle','Make a Letter','Preview'];
const descs=['원하는 케이크를 골라주세요.','좋아하는 데코로 케이크를 꾸며주세요.','케이크 위에 촛불을 올려주세요.','민혁에게 전할 편지를 적어주세요.','완성된 케이크와 편지를 확인해주세요.'];
function img(src){if(cache[src])return cache[src];const i=new Image;i.src=src;cache[src]=i;i.onload=draw;return i}function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function allObjects(){return [...state.objects,...state.candles]};function selectedObj(){return allObjects().find(o=>o.id===selected)}
function drawCake(){const im=img(cakeAssets[state.cake_type]);if(!im.complete)return;const sizes={whole:[690,510],slice:[680,500],cut:[700,520],'two-tier':[700,560]},[w,h]=sizes[state.cake_type];ctx.drawImage(im,(1080-w)/2,285,w,h)}
function drawObj(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.scale(o.scale||1,o.scale||1);const im=img(o.src),w=o.w||180,h=o.h||180;if(im.complete)ctx.drawImage(im,-w/2,-h/2,w,h);if(o.id===selected){ctx.strokeStyle='#236aa5';ctx.setLineDash([12,8]);ctx.lineWidth=5;ctx.strokeRect(-w/2-10,-h/2-10,w+20,h+20);ctx.setLineDash([]);ctx.fillStyle='#236aa5';ctx.beginPath();ctx.arc(w/2+25,h/2+25,22,0,Math.PI*2);ctx.fill();ctx.fillStyle='white';ctx.font='bold 26px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('↻',w/2+25,h/2+25)}ctx.restore()}
function draw(){let g=ctx.createLinearGradient(0,0,0,1080);g.addColorStop(0,'#fffaf2');g.addColorStop(.55,'#f8eee4');g.addColorStop(1,state.bg);ctx.fillStyle=g;ctx.fillRect(0,0,1080,1080);drawCake();allObjects().sort((a,b)=>(a.z||0)-(b.z||0)).forEach(drawObj)}
function addAsset(id){const large=id.includes('whale')||id.includes('paint');const o={id:crypto.randomUUID(),src:`/assets/${id}.svg`,assetId:id,x:540,y:490,w:large?240:185,h:large?190:185,scale:1,rotation:0,z:20+state.objects.length};state.objects.push(o);selected=o.id;draw()}
function addCandle(id){if(state.candles.length>=33)return alert('촛불은 최대 33개까지 놓을 수 있어요.');const n=state.candles.length,o={id:crypto.randomUUID(),src:`/assets/${id}.svg`,assetId:id,x:390+(n%7)*50,y:390+Math.floor(n/7)*24,w:id.includes('classic')?70:100,h:id.includes('classic')?140:130,scale:1,rotation:0,z:100+n};state.candles.push(o);selected=o.id;draw()}
function render(){document.querySelector('#stepNo').textContent=step;document.querySelector('#stepTitle').textContent=titles[step-1];document.querySelector('#stepDesc').textContent=descs[step-1];selected=null;if(step===1)controls.innerHTML=`<div class="panel"><span class="section-label">CAKE TYPE</span><div class="cake-types visual">${[['whole','WHOLE'],['slice','PIECE'],['cut','CUT'],['two-tier','2-LAYER']].map(([v,n])=>`<button data-type="${v}" class="${state.cake_type===v?'active':''}"><img src="${cakeAssets[v]}"><span>${n}</span></button>`).join('')}</div><span class="section-label">BACKGROUND</span><div class="row"><input id="bg" type="color" value="${state.bg}"><span class="hint">paper gradient</span></div></div>`;if(step===2)controls.innerHTML=`<div class="panel"><span class="section-label">STICKER TRAY · 여러 개 선택할 수 있어요</span><div class="sticker-tray">${stickers.map(([n,a])=>`<button class="asset" data-asset="${a}"><img src="/assets/${a}.svg"><span>${n}</span></button>`).join('')}</div><label class="upload">+ MY IMAGE<input id="upload" type="file" accept="image/png,image/jpeg,image/webp,image/heic,image/heif,.heic,.heif" hidden></label><p class="hint">캔버스에서 데코를 누른 뒤 파란 핸들을 드래그하면 크기 조정 + 회전됩니다.</p></div>`;if(step===3)controls.innerHTML=`<div class="panel"><span class="section-label">CANDLES</span><div class="candle-tray">${candleAssets.map(([n,a])=>`<button class="asset" data-candle="${a}"><img src="/assets/${a}.svg"><span>${n}</span></button>`).join('')}</div><p class="hint">촛불도 이동·크기 조정·회전할 수 있어요.</p></div>`;if(step===4)controls.innerHTML=`<div class="panel letter-form"><label>제목 · <span id="titleCount">${state.title.length}</span>/40<input class="field" id="title" maxlength="40" value="${esc(state.title)}" placeholder="편지 제목을 적어주세요"></label><label>닉네임 · <span id="nickCount">${state.nickname.length}</span>/20<input class="field" id="nick" maxlength="20" value="${esc(state.nickname)}"></label><label>국가<select class="field" id="country">${countries.map(([v,n])=>`<option value="${v}" ${state.country===v?'selected':''}>${n}</option>`).join('')}</select></label><span class="section-label">LETTER PAPER</span><div class="template-picks"><button data-template="paper" class="${state.letterTemplate==='paper'?'active':''}">Paper</button><button data-template="envelope" class="${state.letterTemplate==='envelope'?'active':''}">Envelope</button></div><div class="letter-sheet ${state.letterTemplate}"><textarea id="letter" maxlength="500" placeholder="민혁에게 전할 편지를 적어주세요.">${esc(state.letter)}</textarea><span><b id="letterCount">${state.letter.length}</b>/500</span></div></div>`;if(step===5)controls.innerHTML=`<div class="panel preview-card"><h3>${esc(state.title||'Untitled letter')}</h3><div class="preview-letter ${state.letterTemplate}"><p>${esc(state.letter||'—').replace(/\n/g,'<br>')}</p><small>from. ${esc(state.nickname||'—')}${state.country?' · '+state.country:''}</small></div></div>`;bind();draw()}
function bind(){document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{state.cake_type=b.dataset.type;render()});document.querySelector('#bg')?.addEventListener('input',e=>{state.bg=e.target.value;draw()});document.querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>addAsset(b.dataset.asset));document.querySelectorAll('[data-candle]').forEach(b=>b.onclick=()=>addCandle(b.dataset.candle));document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{state.letterTemplate=b.dataset.template;render()});[['title','title','titleCount'],['nick','nickname','nickCount'],['letter','letter','letterCount']].forEach(([id,key,count])=>document.querySelector('#'+id)?.addEventListener('input',e=>{state[key]=e.target.value;document.querySelector('#'+count).textContent=e.target.value.length}));document.querySelector('#country')?.addEventListener('change',e=>state.country=e.target.value);document.querySelector('#upload')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(f.size>30_000_000)return alert('30MB 이하 이미지를 사용해주세요.');const r=new FileReader;r.onload=()=>{const o={id:crypto.randomUUID(),src:r.result,assetId:'user-image',x:540,y:470,w:260,h:260,scale:1,rotation:0,z:50+state.objects.length};state.objects.push(o);selected=o.id;draw()};r.readAsDataURL(f)})}
function pos(e){const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*1080/r.width,y:(e.clientY-r.top)*1080/r.height}}
function localPoint(o,p){const a=-(o.rotation||0)*Math.PI/180,dx=p.x-o.x,dy=p.y-o.y,s=o.scale||1;return{x:(dx*Math.cos(a)-dy*Math.sin(a))/s,y:(dx*Math.sin(a)+dy*Math.cos(a))/s}}
function hit(p){return allObjects().slice().sort((a,b)=>(b.z||0)-(a.z||0)).find(o=>{const q=localPoint(o,p);return Math.abs(q.x)<(o.w||180)/2+18&&Math.abs(q.y)<(o.h||180)/2+18})}
function onHandle(o,p){const q=localPoint(o,p),w=o.w||180,h=o.h||180;return Math.hypot(q.x-(w/2+25),q.y-(h/2+25))<45}
cv.onpointerdown=e=>{const p=pos(e),current=selectedObj();if(current&&onHandle(current,p)){const dx=p.x-current.x,dy=p.y-current.y;gesture={mode:'transform',o:current,startDist:Math.hypot(dx,dy),startAngle:Math.atan2(dy,dx)*180/Math.PI,startScale:current.scale||1,startRotation:current.rotation||0};cv.setPointerCapture(e.pointerId);return}const o=hit(p);selected=o?.id||null;if(o){gesture={mode:'drag',o,dx:p.x-o.x,dy:p.y-o.y};cv.setPointerCapture(e.pointerId)}draw()};
cv.onpointermove=e=>{if(!gesture)return;const p=pos(e),o=gesture.o;if(gesture.mode==='drag'){o.x=Math.max(0,Math.min(1080,p.x-gesture.dx));o.y=Math.max(0,Math.min(1080,p.y-gesture.dy))}else{const dx=p.x-o.x,dy=p.y-o.y,dist=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI;o.scale=Math.max(.3,Math.min(3.5,gesture.startScale*(dist/Math.max(gesture.startDist,1))));o.rotation=gesture.startRotation+(angle-gesture.startAngle)}draw()};cv.onpointerup=()=>gesture=null;
document.querySelector('#back').onclick=()=>{if(step>1){step--;render()}else if(confirm('작성 중인 케이크를 나가면 현재 작업이 사라져요. 홈으로 갈까요?'))location.href='/'};
document.querySelector('#next').onclick=async()=>{if(step===4&&(!state.title.trim()||!state.nickname.trim()||!state.letter.trim()))return alert('제목, 닉네임, 편지를 입력해주세요.');if(step<5){step++;render();return}selected=null;draw();const final_image=cv.toDataURL('image/webp',.9),payload={title:state.title,nickname:state.nickname,country:state.country,letter:state.letter,letter_template:state.letterTemplate,bg:state.bg,cake_type:state.cake_type,objects:state.objects.map(({src,...o})=>o),candles:state.candles.map(({src,...o})=>o),final_image};try{const r=await fetch('/api/cakes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),text=await r.text();let d;try{d=JSON.parse(text)}catch{throw new Error(text||`HTTP ${r.status}`)}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);location.href=`/cake/${d.public_id}`}catch(e){alert(`케이크 저장에 실패했어요.\n${e.message}`)}};render();