const cv=document.querySelector('#cake'),ctx=cv.getContext('2d'),controls=document.querySelector('#controls');
let step=1,selected=null,drag=null;const cache={};
const state={bg:'#f1d7d3',cake_type:'whole',objects:[],candles:[],nickname:'',country:'',letter:''};
const cakeAssets={whole:'/assets/v04-cake-whole.svg',slice:'/assets/v04-cake-piece.svg',cut:'/assets/v04-cake-cut.svg','two-tier':'/assets/v04-cake-two-tier.svg'};
const stickers=[['Strawberry','v04-strawberry'],['Rose','v04-rose'],['Ribbon','v04-ribbon'],['Maltese','v04-maltese'],['Humpback Whale','v04-whale'],['Cucumber','v04-cucumber'],['Sunglasses','v04-sunglasses'],['Palette & Brush','v04-paint'],['Cherry','cherry'],['Blueberry','blueberry'],['Chihuahua','chihuahua'],['German Shepherd','shepherd'],['Heart','heart']];
const candleAssets=[['Classic','v04-candle-classic'],['Heart','v04-candle-heart'],['Dog','v04-candle-dog']];
const countries=[['','선택 안 함'],['KR','South Korea'],['JP','Japan'],['US','United States'],['CN','China'],['TW','Taiwan'],['HK','Hong Kong'],['TH','Thailand'],['PH','Philippines'],['ID','Indonesia'],['MY','Malaysia'],['SG','Singapore'],['VN','Vietnam'],['GB','United Kingdom'],['FR','France'],['DE','Germany'],['ES','Spain'],['IT','Italy'],['CA','Canada'],['AU','Australia'],['BR','Brazil'],['MX','Mexico']];
function img(src){if(cache[src])return cache[src];let i=new Image;i.src=src;cache[src]=i;i.onload=draw;return i}function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function drawCake(){const im=img(cakeAssets[state.cake_type]);if(!im.complete)return;const sizes={'whole':[690,510],slice:[650,485],cut:[690,510],'two-tier':[700,560]},[w,h]=sizes[state.cake_type];ctx.drawImage(im,(1080-w)/2,285,w,h)}
function drawObj(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.rotation||0);ctx.scale(o.scale||1,o.scale||1);let im=img(o.src);if(im.complete)ctx.drawImage(im,-(o.w||180)/2,-(o.h||180)/2,o.w||180,o.h||180);if(o.id===selected){ctx.strokeStyle='#17223b';ctx.setLineDash([12,8]);ctx.lineWidth=4;ctx.strokeRect(-(o.w||180)/2-8,-(o.h||180)/2-8,(o.w||180)+16,(o.h||180)+16)}ctx.restore()}
function draw(){let g=ctx.createLinearGradient(0,0,0,1080);g.addColorStop(0,'#fffaf2');g.addColorStop(.55,'#f8eee4');g.addColorStop(1,state.bg);ctx.fillStyle=g;ctx.fillRect(0,0,1080,1080);drawCake();[...state.objects,...state.candles].sort((a,b)=>(a.z||0)-(b.z||0)).forEach(drawObj)}
function addAsset(id){let src=`/assets/${id}.svg`,large=id.includes('whale')||id.includes('paint');state.objects.push({id:crypto.randomUUID(),src,x:540,y:490,w:large?230:180,h:large?200:180,scale:1,rotation:0,z:20+state.objects.length});selected=state.objects.at(-1).id;draw()}
function addCandle(id){if(state.candles.length>=33)return alert('촛불은 최대 33개까지 놓을 수 있어요.');const n=state.candles.length,x=390+(n%7)*50,y=390+Math.floor(n/7)*24;state.candles.push({id:crypto.randomUUID(),src:`/assets/${id}.svg`,x,y,w:id.includes('classic')?70:100,h:id.includes('classic')?140:130,scale:1,rotation:0,z:100+n});selected=state.candles.at(-1).id;draw()}
function render(){document.querySelector('#stepNo').textContent=step;document.querySelector('#stepTitle').textContent=['MAKE A CAKE','MAKE A WISH','WRITE A LETTER','FINAL REVIEW'][step-1];if(step===1)controls.innerHTML=`<div class="panel"><div class="tabs"><button class="tab active" data-pane="cakePane">CAKE</button><button class="tab" data-pane="decoPane">DECORATIONS</button></div><div id="cakePane" class="pane"><span class="section-label">CAKE TYPE</span><div class="cake-types visual">${[['whole','WHOLE'],['slice','PIECE'],['cut','CUT'],['two-tier','2-LAYER']].map(([v,n])=>`<button data-type="${v}" class="${state.cake_type===v?'active':''}"><img src="${cakeAssets[v]}"><span>${n}</span></button>`).join('')}</div><span class="section-label">BACKGROUND</span><div class="row"><input id="bg" type="color" value="${state.bg}"><span class="hint">paper gradient</span></div></div><div id="decoPane" class="pane" hidden><span class="section-label">STICKER TRAY · 한 탭에서 모두 골라요</span><div class="sticker-tray">${stickers.map(([n,a])=>`<button class="asset" data-asset="${a}"><img src="/assets/${a}.svg"><span>${n}</span></button>`).join('')}</div><label class="upload">+ MY IMAGE<input id="upload" type="file" accept="image/png,image/jpeg,image/webp,image/heic,image/heif,.heic,.heif" hidden></label></div></div>`;if(step===2)controls.innerHTML=`<div class="panel"><span class="section-label">CANDLES · 촛불을 골라 케이크에 올려주세요</span><div class="candle-tray">${candleAssets.map(([n,a])=>`<button class="asset" data-candle="${a}"><img src="/assets/${a}.svg"><span>${n}</span></button>`).join('')}</div><p class="hint">추가한 촛불은 케이크 위에서 드래그해 옮길 수 있어요. 최대 33개.</p></div>`;if(step===3)controls.innerHTML=`<div class="panel"><label>닉네임 · <span id="nickCount">${state.nickname.length}</span>/20<input class="field" id="nick" maxlength="20" value="${esc(state.nickname)}"></label><label>국가 · 선택<select class="field" id="country">${countries.map(([v,n])=>`<option value="${v}" ${state.country===v?'selected':''}>${n}</option>`).join('')}</select></label><label>생일 편지 · <span id="letterCount">${state.letter.length}</span>/500<textarea class="field" id="letter" maxlength="500">${esc(state.letter)}</textarea></label></div>`;if(step===4)controls.innerHTML=`<div class="panel review"><b>Made by ${esc(state.nickname||'—')}${state.country?' · '+state.country:''}</b><p>${esc(state.letter||'—').replace(/\n/g,'<br>')}</p></div>`;bind();draw()}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.pane').forEach(p=>p.hidden=true);document.querySelector('#'+b.dataset.pane).hidden=false});document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{state.cake_type=b.dataset.type;render()});document.querySelector('#bg')?.addEventListener('input',e=>{state.bg=e.target.value;draw()});document.querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>addAsset(b.dataset.asset));document.querySelectorAll('[data-candle]').forEach(b=>b.onclick=()=>addCandle(b.dataset.candle));document.querySelector('#nick')?.addEventListener('input',e=>{state.nickname=e.target.value;document.querySelector('#nickCount').textContent=e.target.value.length});document.querySelector('#letter')?.addEventListener('input',e=>{state.letter=e.target.value;document.querySelector('#letterCount').textContent=e.target.value.length});document.querySelector('#country')?.addEventListener('change',e=>state.country=e.target.value);document.querySelector('#upload')?.addEventListener('change',e=>{let f=e.target.files[0];if(!f)return;if(f.size>30_000_000)return alert('30MB 이하 이미지를 사용해주세요.');let r=new FileReader;r.onload=()=>{state.objects.push({id:crypto.randomUUID(),src:r.result,x:540,y:470,w:240,h:240,scale:1,rotation:0,z:50+state.objects.length});draw()};r.readAsDataURL(f)})}
function pos(e){let r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*1080/r.width,y:(e.clientY-r.top)*1080/r.height}}function hit(x,y){return [...state.objects,...state.candles].reverse().find(o=>Math.abs(x-o.x)<((o.w||180)/2)*(o.scale||1)&&Math.abs(y-o.y)<((o.h||180)/2)*(o.scale||1))}
cv.onpointerdown=e=>{let p=pos(e),o=hit(p.x,p.y);selected=o?.id||null;if(o){drag={o,dx:p.x-o.x,dy:p.y-o.y};cv.setPointerCapture(e.pointerId)}draw()};cv.onpointermove=e=>{if(!drag)return;let p=pos(e);drag.o.x=p.x-drag.dx;drag.o.y=p.y-drag.dy;draw()};cv.onpointerup=()=>drag=null;
document.querySelector('#back').onclick=()=>{if(step>1){step--;render()}else if(confirm('작성 중인 케이크를 나가면 현재 작업이 사라져요. 홈으로 갈까요?'))location.href='/'};document.querySelector('#next').onclick=async()=>{if(step===3&&(!state.nickname.trim()||!state.letter.trim()))return alert('닉네임과 편지를 입력해주세요.');if(step<4){step++;render();return}const final_image=cv.toDataURL('image/webp',.9);const payload={nickname:state.nickname,country:state.country,letter:state.letter,bg:state.bg,cake_type:state.cake_type,objects:state.objects.map(({src,...o})=>o),candles:state.candles.map(({src,...o})=>o),final_image};try{let r=await fetch('/api/cakes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});let text=await r.text(),d;try{d=JSON.parse(text)}catch{throw new Error(text||`HTTP ${r.status}`)}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);location.href=`/cake/${d.public_id}`}catch(e){alert(`케이크 저장에 실패했어요.\n${e.message}`)}};render();
